include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_super_parameters: true
    avoid_print: true

    # Safety
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true

    # Readability
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_new: true
